### ISSUE TITLE
Is there an api to pull the errors for the current field?

### ISSUE THREAD

**Issue by TheClark** [joepuzzo/react-savage-form#2]
Creating a custom component.

Leveraged the source code from the Text.js in src

Basically I was hoping there is a getError() similar to the getValue call, so my custom comp can display it's error message.  

Here is the source minus the component impl.  Note the errorText prop

`/* ---------- Imports ---------- */

// Import React
import React, {Component} from 'react';

// Import PropTypes library
import PropTypes from 'prop-types';

// Inport the form input
import {FormField} from 'react-savage-form';

import BatchDefChooserSuperSelect from './BatchDefChooserSuperSelect';

class TextWrapper extends Component {

    render() {

        // console.log('RENDER');

        const {
            fieldDidUpdate,
            fieldApi,
            onInput,
            ...rest
        } = this.props;

        const {
            getValue,
            setValue,
            setTouched,
            format
        } = fieldApi;

        return (

            <BatchDefChooserSuperSelect
                {...rest}
                value={getValue()}
                errorText={getError()}
                onAutoCompleteTyping={() => setTouched()}
                onChange={(value) => {
                    setValue(value);
                }
                }
                onBlur={() => {
                    setTouched();
                }}
            />

        );
    }

}

class Text extends Component {

    render() {
        const {
            field,
            ...rest
        } = this.props;

        //console.log("REST", rest);

        return (
            <FormField field={field}>
                <TextWrapper {...rest} />
            </FormField>
        );
    }

}

Text.propTypes = {
    field: PropTypes.oneOfType([
        PropTypes.string,
        PropTypes.array,
    ]).isRequired,
};

export default Text;`

**Comment by TheClark** [comment]
Looks like a small addition to FormField.  Happy to contribute, open to a pull request for this?

**Comment by TheClark** [comment]
Made a very simple PR

https://github.com/joepuzzo/react-savage-form/pull/3

I can make a second one for warnings if interested...

**Comment by joepuzzo** [comment]
Hey my apologies for taking so long to reply. This is a great idea! Can you just add a get success as well?? if you do i will totally approve your pull request. Also, there is no need to update the old Form.js file as its no longer used. I still need to remove it

**Comment by joepuzzo** [comment]
Also you have pointed out.. i need to add documentation for how to create custom form fields so you don't have to use my default ones

**Comment by joepuzzo** [comment]
I have updated the form library with the request you have made. And also fixed an issue with the getters when using array syntax on fields.. i.e field={["questions",0]}
